'use client'
import { useEffect,useState } from 'react'
import axios from 'axios'
import { Save,Sparkles } from 'lucide-react'
import ImageUploader from '@/components/ImageUploader'
const defaults=[['12','Oyun'],['350+','Öğrenci'],['28','Öğrenci gösterisi'],['6','Yıllık yolculuk']]
export default function ImpactAdmin(){
 const [id,setId]=useState(''),[title,setTitle]=useState('Neler Yaptık?'),[intro,setIntro]=useState(''),[image,setImage]=useState('/demo/story-5.jpg'),[stats,setStats]=useState<string[][]>(defaults),[saving,setSaving]=useState(false)
 useEffect(()=>{axios.get('/api/settings').then(({data})=>{if(data){setId(data.id);setTitle(data.impactTitle||'Neler Yaptık?');setIntro(data.impactIntro||'');setImage(data.impactImage||'/demo/story-5.jpg');setStats(data.impactStats||defaults)}})},[])
 const save=async()=>{setSaving(true);await axios.put('/api/settings',{id,impactTitle:title,impactIntro:intro,impactImage:image,impactStats:stats});setSaving(false)}
 return <div className="min-h-screen bg-[#141313] p-8 text-white"><div className="max-w-3xl mx-auto"><div className="flex items-center gap-3 mb-8"><Sparkles className="text-lime-300"/><div><h1 className="text-4xl font-bold">Neler Yaptık?</h1><p className="text-white/50">Rakamları, anlatımı ve kolaj görselini yönetin.</p></div></div><div className="space-y-6 bg-white/5 border border-white/10 rounded-2xl p-6"><label className="block">Bölüm başlığı<input value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 w-full bg-white/10 border border-white/20 rounded-lg p-3"/></label><label className="block">Kısa anlatım<textarea value={intro} onChange={e=>setIntro(e.target.value)} rows={4} className="mt-2 w-full bg-white/10 border border-white/20 rounded-lg p-3"/></label><ImageUploader currentUrl={image} onUrlChange={setImage} label="Tarihçe / kolaj görseli" folder="gallery"/><div className="grid md:grid-cols-2 gap-4">{stats.map((s,i)=><div className="bg-black/20 rounded-xl p-4" key={i}><input value={s[0]} onChange={e=>setStats(stats.map((x,n)=>n===i?[e.target.value,x[1]]:x))} className="w-full bg-transparent text-4xl font-bold text-lime-300 border-b border-white/20 p-2"/><input value={s[1]} onChange={e=>setStats(stats.map((x,n)=>n===i?[x[0],e.target.value]:x))} className="w-full bg-transparent border-b border-white/20 p-2 mt-2"/></div>)}</div><button onClick={save} disabled={saving} className="w-full bg-lime-300 text-black p-4 font-bold flex items-center justify-center gap-2"><Save/>{saving?'Kaydediliyor…':'Değişiklikleri kaydet'}</button></div></div></div>
}
