'use client'
import { useEffect,useState } from 'react'
import { CalendarDays,Clock,MapPin,Plus,Trash2,X } from 'lucide-react'

type Event={id:string;title:string;type:string;date:string;startTime:string;endTime?:string;location?:string;description?:string;active:boolean;featured:boolean}
const empty={title:'',type:'education',date:new Date().toISOString().slice(0,10),startTime:'18:00',endTime:'',location:'Fofora Tiyatro',description:'',active:true,featured:false}
export default function CalendarAdmin(){
 const [items,setItems]=useState<Event[]>([]),[form,setForm]=useState<any>(empty),[open,setOpen]=useState(false),[saving,setSaving]=useState(false)
 const load=()=>fetch('/api/calendar?admin=true').then(r=>r.json()).then(setItems)
 useEffect(()=>{load()},[])
 const edit=(x:Event)=>{setForm({...x,date:x.date.slice(0,10)});setOpen(true)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);await fetch('/api/calendar',{method:form.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setSaving(false);setOpen(false);setForm(empty);load()}
 const remove=async(id:string)=>{if(!confirm('Bu takvim kaydı silinsin mi?'))return;await fetch(`/api/calendar?id=${id}`,{method:'DELETE'});load()}
 return <div className="studio-page"><header className="studio-head"><div><small>İÇERİK STÜDYOSU</small><h1>Takvim</h1><p>Oyun, eğitim ve provaları telefondan birkaç saniyede yayınla.</p></div><button className="studio-primary" onClick={()=>{setForm(empty);setOpen(true)}}><Plus/> Yeni kayıt</button></header>
 <div className="event-list">{items.length===0&&<div className="studio-empty"><CalendarDays/><h2>Takvim henüz boş</h2><p>İlk etkinliği ekleyerek başlayabilirsin.</p></div>}{items.map(x=><article key={x.id} onClick={()=>edit(x)}><time><b>{new Date(x.date).toLocaleDateString('tr-TR',{day:'2-digit'})}</b><span>{new Date(x.date).toLocaleDateString('tr-TR',{month:'short'})}</span></time><div><small>{x.type==='play'?'OYUN':x.type==='rehearsal'?'PROVA':'EĞİTİM'} {!x.active&&' • TASLAK'}</small><h2>{x.title}</h2><p><Clock/> {x.startTime}{x.endTime&&`–${x.endTime}`} {x.location&&<><MapPin/> {x.location}</>}</p></div><button onClick={e=>{e.stopPropagation();remove(x.id)}} aria-label="Sil"><Trash2/></button></article>)}</div>
 {open&&<div className="studio-modal"><form onSubmit={save}><button type="button" className="studio-close" onClick={()=>setOpen(false)}><X/></button><small>TAKVİM KAYDI</small><h2>{form.id?'Kaydı düzenle':'Yeni kayıt'}</h2><label>Başlık<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="studio-grid"><label>Tür<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="education">Eğitim</option><option value="play">Oyun</option><option value="rehearsal">Prova</option><option value="other">Diğer</option></select></label><label>Tarih<input type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Başlangıç<input type="time" required value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></label><label>Bitiş<input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></label></div><label>Konum<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Not<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="studio-checks"><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Yayında</label><label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Öne çıkar</label></div><button className="studio-primary" disabled={saving}>{saving?'Kaydediliyor…':'Kaydet'}</button></form></div>}</div>
}
